type Query {
    session(id: ID!): Session!
}

type Mutation {
    createSession(displayName: String!): CreateSessionResult!
    joinSession(sessionId: ID!, displayName: String!, dietaryPreference: String): JoinSessionResult!
    claimItem(itemId: ID!, userId: ID!): ClaimResult!
    releaseItem(itemId: ID!, userId: ID!): ClaimResult!

    uploadReceipt(sessionId: ID!, fileBase64: String!, fileName: String!): ReceiptUploadResult!
}

type Session {
    id: ID!
    status: SessionStatus!
    members: [Member!]!
    items: [Item!]!
    tax: Float
    tip: Float
    joinUrl: String!
    qrCodeUrl: String!
    leader: Member!
}

enum SessionStatus {
    WAITING
    ACTIVE
    CLOSED
}

enum MemberRole {
    LEADER
    MEMBER
}

type Member {
    id: ID!
    displayName: String!
    connected: Boolean!
    token: String
    role: String!
    dietaryPreference: String
}

type Item {
    id: ID!
    name: String!
    price: Float!
    category: String
    claimedBy: Member
    locked: Boolean!
}

type ClaimResult {
    success: Boolean!
    item: Item!
    errorCode: String
    message: String
}

type ReceiptUploadResult {
    success: Boolean!
    jobId: ID
    message: String!
}

type JoinSessionResult {
    success: Boolean!
    token: String!
    member: Member!
    session: Session!
}

type CreateSessionResult {
    success: Boolean!
    token: String!
    member: Member!
    session: Session!
}