spring.application.name=backend
 
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.graphql.graphiql.enabled=true
spring.graphql.path=/graphql
 
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
 
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.out-of-order=true
spring.flyway.validate-on-migrate=false

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

supabase.url=${SUPABASE_URL:}
supabase.service-key=${SUPABASE_KEY:}
supabase.bucket=${SUPABASE_BUCKET:receipts}
ocr.queue.name=${OCR_QUEUE_NAME:receipt_ocr_queue}
app.base-url=http://localhost:3000

